#!/bin/bash

# Fail if not in a git repo
if ! `git rev-parse --is-inside-work-tree > /dev/null`
then
	exit 1
fi

# Remember path and setup temporary path
REPO_DIRECTORY=`pwd`
REPO_SLUG=`echo ${REPO_DIRECTORY} | sed --expression 's/\///'| sed --expression='s/\//-/g'`
WORK_TREE=/tmp/${REPO_SLUG}
mkdir -p ${WORK_TREE}
git checkout-index -a -f --prefix="${WORK_TREE}/"
cd ${WORK_TREE}

# Execute input from stdin and remember exit code
input=`cat`
sh -c "$input"
COMMAND_STATUS=$?

# Restore path and clean up
cd ${REPO_DIRECTORY}
#rm -rf ${WORK_TREE}
exit ${COMMAND_STATUS}
